
name: tagged-release

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create settings.jar
        run: buildjar.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Contents of jar
          unzip -l settings.jar
